[env]
TERM = "screen-256color"

[font]
size = 24
normal = { family = "iMWritingMono Nerd Font"  }
# [font.bold]
# style = "Bold"

# to install the themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

# [[keyboard.bindings]]
# chars = "\u001BOH"
# key = "Left"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u001BOF"
# key = "Right"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u0015"
# key = "Back"
# mods = "Command

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "None"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "A"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "B"
mode = "~Search"
mods = "Command"

[window]
startup_mode = "Maximized"
opacity = 1.0
option_as_alt = "Both"
decorations_theme_variant = "None"
[window.padding]
x = 10
y = 10

[general]
import = ["themes/themes/solarized_dark.toml"]
